language: python
python:
  - "2.7"
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script:
  - pip install -U planemo
  - pip install -r requirements.txt
  - python setup.py install
  - export PYTHONPATH=$(gxargparse_check_path -q)
  - python examples/example.py --generate_galaxy_xml > tmp.xml
  - diff tmp.xml examples/example.xml
  - planemo lint --report_level all --fail_level error --xsd tmp.xml
  - python examples/example.py --generate_cwl_tool > tmp.cwl
  - diff tmp.cwl examples/example.cwl
